// 商品库（对应《商品库与数值配置.md》3.1/3.2 节，MVP 先行 24 个）
// 字段定义见商品库文档第 1 节
module.exports = [
  // ===== 宠物用品线（第 2 章主战场）=====
  { id: 'SKU-001', nameZh: '硅胶宠物梳', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 45000, top10AvgReviews: 350, priceUSD: 16.99, supplyPriceCNY: 15.0,
    weightKg: 0.24, dimCm: [20, 8, 2], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 4, competition: 4, profit: 5, logistics: 5, risk: 5 },
    tags: ['star'], // 章节主推品
    intro: '低调的利润之王：物流友好、利润厚、竞争温和。' },
  { id: 'SKU-002', nameZh: '电动猫玩具', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 30000, top10AvgReviews: 1200, priceUSD: 24.99, supplyPriceCNY: 32.0,
    weightKg: 0.35, dimCm: [22, 15, 8], hazmat: ['battery'], patentRisk: false,
    competition: 4, expertScores: { market: 3, competition: 2, profit: 3, logistics: 2, risk: 5 },
    tags: ['trap_battery'] },
  { id: 'SKU-003', nameZh: '宠物香水喷雾', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 12000, top10AvgReviews: 180, priceUSD: 18.99, supplyPriceCNY: 12.0,
    weightKg: 0.25, dimCm: [15, 6, 6], hazmat: ['liquid'], patentRisk: false,
    competition: 2, expertScores: { market: 2, competition: 4, profit: 4, logistics: 1, risk: 5 },
    tags: ['trap_liquid'] },
  { id: 'SKU-004', nameZh: '慢食碗', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 28000, top10AvgReviews: 600, priceUSD: 13.99, supplyPriceCNY: 13.0,
    weightKg: 0.22, dimCm: [20, 20, 2], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 3, competition: 3, profit: 4, logistics: 4, risk: 5 },
    tags: ['candidate'] },
  { id: 'SKU-005', nameZh: '仿大牌宠物背包', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 60000, top10AvgReviews: 800, priceUSD: 34.99, supplyPriceCNY: 45.0,
    weightKg: 0.90, dimCm: [35, 28, 20], hazmat: [], patentRisk: true,
    competition: 3, expertScores: { market: 5, competition: 3, profit: 4, logistics: 2, risk: 1 },
    tags: ['trap_patent'] },
  { id: 'SKU-006', nameZh: '宠物GPS项圈', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 20000, top10AvgReviews: 900, priceUSD: 44.99, supplyPriceCNY: 68.0,
    weightKg: 0.12, dimCm: [18, 12, 5], hazmat: ['battery', 'magnetic'], patentRisk: false,
    competition: 4, expertScores: { market: 2, competition: 2, profit: 2, logistics: 2, risk: 5 },
    tags: ['trap_magnetic'] },
  { id: 'SKU-007', nameZh: '猫抓板瓦楞纸', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 35000, top10AvgReviews: 420, priceUSD: 21.99, supplyPriceCNY: 22.0,
    weightKg: 1.10, dimCm: [50, 30, 4], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 4, competition: 4, profit: 4, logistics: 2, risk: 5 },
    tags: ['candidate'] },
  { id: 'SKU-008', nameZh: '宠物圣诞服饰', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 80000, top10AvgReviews: 300, priceUSD: 17.99, supplyPriceCNY: 10.0,
    weightKg: 0.15, dimCm: [25, 18, 3], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 4, competition: 4, profit: 4, logistics: 4, risk: 4 },
    seasonality: [0.3,0.3,0.3,0.3,0.3,0.3,0.5,0.5,0.8,1.5,3.5,4.0],
    tags: ['trap_season'] },
  { id: 'SKU-009', nameZh: '智能饮水机', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 50000, top10AvgReviews: 1500, priceUSD: 31.99, supplyPriceCNY: 55.0,
    weightKg: 0.85, dimCm: [30, 22, 18], hazmat: ['battery'], patentRisk: false,
    competition: 5, expertScores: { market: 4, competition: 1, profit: 3, logistics: 2, risk: 5 },
    tags: ['trap_competition'] },
  { id: 'SKU-010', nameZh: '防抓沙发贴', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 32000, top10AvgReviews: 280, priceUSD: 12.99, supplyPriceCNY: 11.0,
    weightKg: 0.10, dimCm: [90, 40, 2], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 3, competition: 4, profit: 1, logistics: 3, risk: 5 },
    tags: ['candidate', 'trap_volumeweight'], // 初筛通过；体积重陷阱在核算关暴露（教学设计）
    intro: '实重极轻但面积大——体积重陷阱的教科书案例。' },
  { id: 'SKU-011', nameZh: '宠物毛巾', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 15000, top10AvgReviews: 200, priceUSD: 9.99, supplyPriceCNY: 6.0,
    weightKg: 0.20, dimCm: [30, 30, 4], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 2, competition: 4, profit: 1, logistics: 3, risk: 5 },
    tags: ['trap_lowprice'] },
  { id: 'SKU-012', nameZh: '猫薄荷玩具包', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 26000, top10AvgReviews: 310, priceUSD: 11.99, supplyPriceCNY: 5.5,
    weightKg: 0.08, dimCm: [18, 12, 4], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 3, competition: 4, profit: 3, logistics: 5, risk: 5 },
    tags: ['candidate'] },
  { id: 'SKU-013', nameZh: '宠物尿垫', brand: 'PawPal', category: '宠物用品', chapter: 5,
    monthlySearch: 40000, top10AvgReviews: 500, priceUSD: 23.99, supplyPriceCNY: 18.0,
    weightKg: 1.60, dimCm: [40, 30, 25], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 4, competition: 3, profit: 3, logistics: 2, risk: 5 },
    tags: ['repurchase'] },
  { id: 'SKU-014', nameZh: '宠物牙刷套装', brand: 'PawPal', category: '宠物用品', chapter: 2,
    monthlySearch: 18000, top10AvgReviews: 260, priceUSD: 14.99, supplyPriceCNY: 8.5,
    weightKg: 0.09, dimCm: [20, 10, 3], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 2, competition: 4, profit: 4, logistics: 5, risk: 5 },
    tags: ['candidate'] },

  // ===== 厨房小物线（第 2 章 Boss 关）=====
  { id: 'SKU-101', nameZh: '硅胶铲勺5件套', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 38000, top10AvgReviews: 400, priceUSD: 19.99, supplyPriceCNY: 18.0,
    weightKg: 0.45, dimCm: [32, 12, 8], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 4, competition: 4, profit: 4, logistics: 4, risk: 5 },
    tags: ['star'], intro: '第 2 章 Boss 主推品：五维均衡的优等生。' },
  { id: 'SKU-102', nameZh: '迷你榨汁杯', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 45000, top10AvgReviews: 1100, priceUSD: 26.99, supplyPriceCNY: 38.0,
    weightKg: 0.55, dimCm: [20, 20, 22], hazmat: ['battery'], patentRisk: false,
    competition: 4, expertScores: { market: 4, competition: 2, profit: 3, logistics: 2, risk: 5 },
    tags: ['trap_battery'] },
  { id: 'SKU-103', nameZh: '不锈钢沥水篮', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 22000, top10AvgReviews: 350, priceUSD: 27.99, supplyPriceCNY: 25.0,
    weightKg: 0.70, dimCm: [35, 25, 12], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 3, competition: 4, profit: 4, logistics: 3, risk: 5 },
    tags: ['candidate'] },
  { id: 'SKU-104', nameZh: '厨房剪纸刀(仿爆款)', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 55000, top10AvgReviews: 700, priceUSD: 15.99, supplyPriceCNY: 12.0,
    weightKg: 0.15, dimCm: [25, 10, 4], hazmat: [], patentRisk: true,
    competition: 3, expertScores: { market: 4, competition: 3, profit: 4, logistics: 4, risk: 1 },
    tags: ['trap_patent'] },
  { id: 'SKU-105', nameZh: '油壶玻璃款', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 16000, top10AvgReviews: 280, priceUSD: 17.99, supplyPriceCNY: 14.0,
    weightKg: 0.50, dimCm: [22, 12, 12], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 2, competition: 4, profit: 4, logistics: 3, risk: 4 },
    tags: ['trap_fragile'], intro: '玻璃制品运输破损率高，隐性成本陷阱。' },
  { id: 'SKU-106', nameZh: '冰格硅胶', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 30000, top10AvgReviews: 450, priceUSD: 12.99, supplyPriceCNY: 7.0,
    weightKg: 0.25, dimCm: [20, 15, 5], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 3, competition: 3, profit: 1, logistics: 4, risk: 5 },
    tags: ['trap_lowprice'] },
  { id: 'SKU-107', nameZh: '保鲜膜切割器', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 34000, top10AvgReviews: 380, priceUSD: 16.99, supplyPriceCNY: 13.0,
    weightKg: 0.30, dimCm: [24, 12, 8], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 4, competition: 4, profit: 4, logistics: 4, risk: 5 },
    tags: ['candidate'] },
  { id: 'SKU-108', nameZh: '感应皂液器', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 28000, top10AvgReviews: 950, priceUSD: 21.99, supplyPriceCNY: 30.0,
    weightKg: 0.40, dimCm: [18, 12, 20], hazmat: ['battery'], patentRisk: false,
    competition: 4, expertScores: { market: 3, competition: 2, profit: 2, logistics: 3, risk: 5 },
    tags: ['trap_battery', 'trap_competition'] },
  { id: 'SKU-109', nameZh: '披萨滚刀', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 9000, top10AvgReviews: 150, priceUSD: 14.99, supplyPriceCNY: 9.0,
    weightKg: 0.12, dimCm: [25, 8, 3], hazmat: [], patentRisk: false,
    competition: 2, expertScores: { market: 1, competition: 4, profit: 3, logistics: 5, risk: 5 },
    tags: ['trap_market'], intro: '月搜不足 2 万：蛋糕太小的典型。' },
  { id: 'SKU-110', nameZh: '硅胶折叠碗', brand: 'ChefMate', category: '厨房小物', chapter: 2,
    monthlySearch: 33000, top10AvgReviews: 420, priceUSD: 18.99, supplyPriceCNY: 15.0,
    weightKg: 0.28, dimCm: [20, 20, 5], hazmat: [], patentRisk: false,
    competition: 3, expertScores: { market: 3, competition: 4, profit: 4, logistics: 5, risk: 5 },
    tags: ['candidate'] },
];
